# This is a DEVELOPMENT Docker Compose script
version: "3.9"
services:
  postgres:
    image: postgres:14.0
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: "task_tracker"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
    volumes:
      - task_tracker-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - task_tracker-network
  app:
    image: maven:3-openjdk-16
    command: "mvn spring-boot:run"
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
      - "20000:20000"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/task_tracker"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - postgres
    networks:
      - task_tracker-network

volumes:
  task_tracker-postgres-data:

networks:
  task_tracker-network:
