# This is a PRODUCTION Docker Compose script
version: "3.9"
services:
  postgres:
    image: postgres:14.0
    container_name: postgres
    environment:
      POSTGRES_DB: "task_tracker"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
    volumes:
      - task_tracker-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - task_tracker-network
  app:
    image: task_tracker
    ports:
      - "20000:20000"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5433/$POSTGRES_DATABASE_NAME"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - postgres
    networks:
      - task_tracker-network

volumes:
  task_tracker-postgres-data:

networks:
  task_tracker-network: